class ResetmoviesController < ApplicationController
  def index
  		Movie.delete_all
  		Movie.create(title: 'Braveheart', hours: '2', minutes: '57', format: 'VHS', release: '1995', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/braveheart.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/vbnGDeq40hI" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Step Brothers', hours: '1', minutes: '38', format: 'DVD', release: '2008', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/MV5BMTcwNzUzMjU1OV5BMl5BanBnXkFtZTcwMTM0NDQ2MQ%40%40._V1_SX214_AL_.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/bgqBtquItHM" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'The Shawshank Redemption', hours: '2', minutes: '22', format: 'VHS', release: '1994', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/shawshank.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/6hB3S9bIaco" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Inception', hours: '2', minutes: '28', format: 'DVD', release: '2010', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/inception.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/8hP9D6kZseM" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'The Dark Knight Rises', hours: '2', minutes: '45', format: 'DVD', release: '2012', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/darkknight.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/g8evyE9TuYk" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'The Prestige', hours: '2', minutes: '10', format: 'DVD', release: '2006', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/prestige.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/o4gHCmTQDVI" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'The Lion King', hours: '1', minutes: '29', format: 'VHS', release: '1994', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/lionking.jpg', trailer: '<iframe width="420" height="315" src="//www.youtube.com/embed/4sj1MT05lAA" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Walle', hours: '1', minutes: '38', format: 'DVD', release: '2008', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/walle.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/alIq_wG9FNk" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Up', hours: '1', minutes: '36', format: 'DVD', release: '2009', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/up.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/pkqzFUhGPJg" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Star Wars: Episode III - Revenge of the Sith', hours: '2', minutes: '20', format: 'VHS', release: '2005', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/starwars.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/nh9rGKuLDNM" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'The Princess Bride', hours: '1', minutes: '38', format: 'VHS', release: '1987', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/theprincessbride.jpg', trailer: '<iframe width="420" height="315" src="//www.youtube.com/embed/VYgcrny2hRs" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'How To Train Your Dragon 2', hours: '1', minutes: '42', format: 'DVD', release: '2014', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/howtotraindragon.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/Z9a4PvzlqoQ" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'The Bourne Ultimatum', hours: '1', minutes: '55', format: 'DVD', release: '2007', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/bourne.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/N6J2oiKJr-A" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Guardians of the Galaxy ', hours: '2', minutes: '1', format: 'Streaming', release: '2014', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/gardiansofgalaxy.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/N6J2oiKJr-A" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Maleficent', hours: '1', minutes: '37', format: 'DVD', release: '2014', rating: '3', image_url: 'https://moviedatabase.s3.amazonaws.com/maleficent.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/w-XO4XiRop0" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Dead Poets Society', hours: '2', minutes: '8', format: 'VHS', release: '1989', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/DeadPoetsSociety.jpg', trailer: '<iframe width="420" height="315" src="//www.youtube.com/embed/wrBk780aOis" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Godzilla', hours: '2', minutes: '3', format: 'Streaming', release: '2014', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/godzilla.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/vIu85WQTPRc" frameborder="0" allowfullscreen></iframe>')
  		Movie.create(title: 'Frozen', hours: '1', minutes: '42', format: 'DVD', release: '2013', rating: '4', image_url: 'https://moviedatabase.s3.amazonaws.com/frozen.jpg', trailer: '<iframe width="560" height="315" src="//www.youtube.com/embed/TbQm5doF_Uc" frameborder="0" allowfullscreen></iframe>')
  		redirect_to :action=>"index", :controller=>"home"
  end
end
